### ISSUE TITLE
Peer Timeout

### ISSUE THREAD

**Issue by rmroc451** [Sequal32/yourcontrol#5]
![image](https://user-images.githubusercontent.com/15070945/92312235-6fe19e00-ef84-11ea-84e4-0b4aaad1e66a.png)
Tried messing with values in config.json, to no avail.

**Comment by Sequal32** [comment]
Hi,
Make sure the server’s simulator is running before you connect, and the aircraft is spawned in. This will occur often the server is not sending any information to you within 10 seconds of you connecting.

**Comment by rmroc451** [comment]
We were bot in the sim, my simconnect gouges I have were showing data.

**Comment by Sequal32** [comment]
You said you tried messing with some of the values in the config.json - did you by any chance increase the conn_timeout? That should delay this message so it gives the server more time to respond. Otherwise, make sure your partner allows the program through the firewall, and if it still doesn't work.... I'll do some more digging.

**Comment by rmroc451** [comment]
Tried lowering refresh rate and up-ing the timeout. We'll try again up-ing it a little more and report back.  

We are both pretty techie and have it port forwarded and allowed through our firewalls. :)

**Comment by Sequal32** [comment]
Not sure if it's an issue with SimConnect then. Try out the latest release and see if that works any better or if tells you that it can't connect to SimConnect.

**Comment by mariocmg** [comment]
I have the same issue

**Comment by Sequal32** [comment]
Let me know if this is resolved in the latest release.
